#!/usr/bin/env python3
"""Emit a Limine appearance header from an Omarchy colors.toml.

    python3 make-header.py --colors <colors.toml> --branding "<text>" --plate <file.png> [out]

The header is the block above limine-entry-tool's generated entries in
/boot/limine.conf (see apply.sh). Colours are the theme's own: accent for the
branding, the eight ANSI slots onto term_palette, foregrounds onto term_foreground.
"""
import re
import sys

KEYS = ("accent", "muted", "selection", "background", "foreground", "bright_foreground",
        "light_foreground", "red", "green", "yellow", "blue", "magenta", "cyan",
        "bright_red", "bright_green", "bright_yellow", "bright_blue", "bright_magenta", "bright_cyan")


def load(path):
    pat = re.compile(r'^\s*([a-z_]+)\s*=\s*"#([0-9a-fA-F]{6})"')
    c = {}
    for line in open(path):
        m = pat.match(line)
        if m:
            c[m.group(1)] = m.group(2).lower()
    missing = [k for k in KEYS if k not in c]
    if missing:
        sys.exit(f"{path}: missing {missing}")
    return c


def main():
    args = sys.argv[1:]
    colors = branding = plate = None
    out = "-"
    while args:
        a = args.pop(0)
        if a == "--colors": colors = args.pop(0)
        elif a == "--branding": branding = args.pop(0)
        elif a == "--plate": plate = args.pop(0)
        else: out = a
    if not (colors and branding and plate):
        sys.exit(__doc__)
    c = load(colors)
    text = f"""### BioVirus — Limine appearance header. Generated by limine/make-header.py from
### {colors.split('/')[-1]}; hand-owned on the box (see the machine's skill): limine-update
### regenerates only the entries below this block; omarchy-refresh-limine would replace it
### with Omarchy's Tokyo Night default.
### Limine config reference: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: {branding}
interface_branding_color: {c['accent']}
interface_help_color: {c['muted']}
interface_help_color_bright: {c['accent']}
hash_mismatch_panic: no

# Plate lives on the ESP next to this file; stretched to the panel (rendered at 2880x1800).
wallpaper: boot():/{plate}
wallpaper_style: stretched
backdrop: {c['background']}
# TT byte is TRANSPARENCY (00 = opaque, 80 = the default 50% dim under a wallpaper, ff = none).
# The plate is composed for full strength, so the terminal is fully see-through.
term_background: ff000000
term_font_scale: 2x2

# Terminal colors: black red green yellow blue magenta cyan white
term_palette: {c['background']};{c['red']};{c['green']};{c['yellow']};{c['blue']};{c['magenta']};{c['cyan']};{c['light_foreground']}
term_palette_bright: {c['selection']};{c['bright_red']};{c['bright_green']};{c['bright_yellow']};{c['bright_blue']};{c['bright_magenta']};{c['bright_cyan']};{c['bright_foreground']}

# Text colors (the selected entry is inverse video: its bar is term_foreground)
term_foreground: {c['foreground']}
term_foreground_bright: {c['bright_foreground']}
term_background_bright: {c['selection']}
"""
    if out == "-":
        sys.stdout.write(text)
    else:
        open(out, "w").write(text)
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
